name: CI Pipeline

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install project dependencies
        run: |
          poetry install --no-interaction --no-ansi --all-extras
          poetry run pip install numpy

      - name: Run tests
        run: |
          poetry run pytest -v

      - name: Generate coverage report
        run: |
          poetry run coverage run -m pytest
          poetry run coverage report

  lint:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install poetry
      - run: poetry install --no-interaction --no-ansi
      - run: poetry run ruff check .