name: Run golden tests and checks

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry numpy
          poetry install --no-interaction --no-ansi --with test
          poetry show

      - name: Run tests
        run: |
          poetry run pytest -v

      - name: Generate coverage report
        run: |
          poetry run coverage report

  lint:
    name: Lint Checks
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --no-interaction --no-ansi

      - name: Run Ruff linter
        run: |
          poetry run ruff check .